import {JetBrains_Mono} from 'next/font/google';
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "@/components/PageTransition";
import StairEffect from "@/components/StairEffect";
import AnimatedCursor from 'react-animated-cursor';

const jetBrains_Mono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jebrains_Mono',

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetBrains_Mono.variable}
      >
        <div className="hidden md:block">
          <AnimatedCursor 
          innerSize={8} 
          outerSize={35} 
          innerScale={2} 
          outerScale={2} 
          outerAlpha={0} 
          innerStyle={{ backgroundColor: "white", }} 
          outerStyle={{
            border: '3px solid white',
          }} />
        </div>
        <Header />
        <StairEffect />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
